project_name: aixunliancang
device: cuda
output_dir: outputs

hardware:
  gpu_name: "RTX 4070"
  vram_gb: 12
  cuda_version: "12.4"
  cuda_cores: 5888
  tensor_cores: 184

model:
  # 针对12GB显存的模型配置
  batch_size: 128  # 较大批次利用张量核心
  mixed_precision: true  # 启用FP16混合精度
  gradient_checkpointing: true  # 大模型使用
  max_sequence_length: 8192  # 根据任务和内存调整

optimization:
  # 针对RTX 4070的优化
  optimizer: "adamw"  # 高效优化器
  learning_rate: 2e-4
  weight_decay: 0.01
  scheduler: "cosine_with_warmup"
  warmup_steps: 100
  gradient_accumulation_steps: 1  # 可增加以模拟更大批次
  mixed_precision_dtype: "float16"  # 使用FP16
  compiler_enabled: true  # 使用PyTorch 2.0+ 编译器

training:
  epochs: 100
  early_stopping_patience: 10
  checkpoint_interval: 1000  # 每1000步保存一次
  eval_interval: 500  # 每500步评估一次
  log_interval: 50  # 每50步记录一次
  gradient_clip: 1.0
  
data:
  num_workers: 8  # 根据CPU核心数调整
  prefetch_factor: 2
  pin_memory: true
  persistent_workers: true
